### ISSUE TITLE
don't abuse people, said all directly there

### ISSUE THREAD

**Issue by jerome-diver** [froala/wysiwyg-rails#70]
You have to be honest and said that froala is for buy (no... not really for buy, but an expensive rent for one year in fact... 140$ for only one year for hobby use... why don't you directly tell this here ? I loose my time with this shit).
You have to said it because people doesn't have to loose there time with something they doesn't want.
And also, explication for how to call it from rails form are... not poor... bad more than poor.
THen all of this for a bad surprise about an incredibly expensive price for only one year (and directly if you not make bisness with it).
Actually, there is BETTER solutions than froala... FOR FREE.
Too bad.

**Comment by stefanneculai** [comment]
Thanks for your feedback, Jerome. We made this plugin in order to ease the integration of the Froala Editor in Rails apps. The license section of the plugins specifies clearly that in order to use the Froala Editor it is required to purchase a license: https://github.com/froala/wysiwyg-rails#license. I am sorry if this created any confusion on your side.

**Comment by jerome-diver** [comment]
Ok @stefanneculai , just add a single line inside the description will just remove any possible confusion and is not to much. If you want it (to be directly clear), you will do it, there is no confusion about what people want and how they do it.
thank you for your answer.
